### ISSUE TITLE
Please update your Google Analytics Tracking ID

### ISSUE THREAD

**Issue by ran-huang** [merico-dev/docs-cn#2]
hello, merico dev! I'm Ran, a technical writer from PingCAP. 

I accidentally found some irrelevant data in our Google Analytics that looks like merico docs. It seems that when you forked [pingcap/website-docs](https://github.com/pingcap/website-docs), you didn't update the Google Analytics tracking id in [`gatsby-config.js`](https://github.com/merico-dev/website-docs/blob/9c5e9f3d8fc02f59422427f35ddc751825702ca7/gatsby-config.js#L16). 😂 

Could you please update that line of code to your GA tracking id, or just disable the `gatsby-plugin-google-analytics` plugin so that your data is not sent to our system? Much appreciated!

**Comment by leglars** [comment]
Hi @ran-huang , Thanks for reminder. I have noticed to our developer and we will remove your GA tracking id when he see the message in the coming morning. I apologize for our carelessness.
BTW, please pass on our thanks for your great works to your team. It do help us setup a good doc site in a short time.

**Comment by ran-huang** [comment]
@leglars You're welcome. We're glad you like our site and happy to see it helps. :)

**Comment by leglars** [comment]
@ran-huang we have removed GA tracks and I will close this issue.
