### ISSUE TITLE
typo: test_cript

### ISSUE THREAD

**Issue by JoshYuJump** [merico-dev/docs-cn#3]
File: [/master/introduction/terms_explanation.md](https://docs.merico.cn/ee/dev/introduction/terms_explanation)

```
测试数据test_cript和实际功能函数find_sym_pairs()贡献了相等数量的行数（7 行），然而这两段代码所包含的工作量显然不同。
```

test_cript? or test_dict?

**Comment by Bobyaol** [comment]
是 test_dict，已经修改了
File: [/master/introduction/terms_explanation.md](https://docs.merico.cn/ee/dev/introduction/terms_explanation)
